# KIMERA Development Configuration
# This file provides development-specific overrides

environment: development

database:
  echo: true  # Enable SQL logging in development
  pool_size: 5  # Smaller pool for development

server:
  reload: true  # Enable auto-reload
  host: "127.0.0.1"
  port: 8000

logging:
  level: DEBUG
  structured: true  # Human-readable logs in development

performance:
  max_threads: 8  # Limit resources in development
  gpu_memory_fraction: 0.5  # Leave GPU memory for other processes

monitoring:
  enabled: true
  performance_tracking: true
  memory_tracking: true
  health_check_interval: 15
  thresholds:
    cpu_warning: 80.0
    cpu_critical: 95.0
    memory_warning: 80.0
    memory_critical: 95.0
    gpu_memory_warning: 85.0
    gpu_memory_critical: 95.0
    disk_warning: 85.0
    disk_critical: 95.0
    response_time_warning: 2.0
    response_time_critical: 5.0

security:
  rate_limit_enabled: false  # Disable rate limiting in development

features:
  debug_mode: true
  experimental_features: true
  hot_reload: true